// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Y4Shs5_kFzS1djUgNXFdVVZdccL6_GQ',
    appId: '1:627826840674:web:c1ec7de78031c39c972d3b',
    messagingSenderId: '627826840674',
    projectId: 'original-sns-app',
    authDomain: 'original-sns-app.firebaseapp.com',
    storageBucket: 'original-sns-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbhF5EOgpalt56Q11sxD7qWRcQSQdHUo4',
    appId: '1:627826840674:android:bc58c3890a6aa0f2972d3b',
    messagingSenderId: '627826840674',
    projectId: 'original-sns-app',
    storageBucket: 'original-sns-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmdYWMlLlpeUnOmQiGPdfiadLLvNgX-1I',
    appId: '1:627826840674:ios:cd619dbf7b0cdb07972d3b',
    messagingSenderId: '627826840674',
    projectId: 'original-sns-app',
    storageBucket: 'original-sns-app.appspot.com',
    iosBundleId: 'com.example.originalSnsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmdYWMlLlpeUnOmQiGPdfiadLLvNgX-1I',
    appId: '1:627826840674:ios:79c96297804d02d8972d3b',
    messagingSenderId: '627826840674',
    projectId: 'original-sns-app',
    storageBucket: 'original-sns-app.appspot.com',
    iosBundleId: 'com.example.originalSnsApp.RunnerTests',
  );
}
